set -g mouse on
set -s escape-time 0
set -ga terminal-overrides ",xterm-256color*:Tc"
set -g set-clipboard on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
set -g status-right ""
set -g status-left "#S"
set -g renumber-windows on
set -g status-position top
set -g allow-passthrough on
set -g status-style "bg=default"
set -g status-justify absolute-centre
set -g window-status-current-style "fg=red bold"

bind x kill-pane
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind r source-file ~/.config/tmux/tmux.conf
bind-key -r s display-popup -E -w 80% -h 70% "fish -c '~/scripts/tmux-session-manager.fish'"
bind-key f new-window "fish -i -c 'source ~/scripts/fzf_cd.fish; exec fish'"
bind-key -r a display-popup -E -w 90% -h 80% "fish -c '~/scripts/arxiv.fish'"
bind-key z display-popup -E -w 80% -h 60% "fish -c '~/scripts/cite.fish'"

setw -g mode-keys vi
unbind [
bind V copy-mode
bind p paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @continuum-restore 'on'
set -g @resurrect-dir '~/.config/tmux/resurrect'

run '~/.config/tmux/plugins/tpm/tpm'
