require "pluginList"
require "theme"
require "settings"
require "keymaps"

require "plugins.comment"
require "plugins.telescope"
require "plugins.lualine"
require "plugins.blankline"
require "plugins.gitsigns"
require "plugins.treesitter"
require "plugins.LSP"
require "plugins.CMP"
require "plugins.DAP"