require "plugins"
require "theme"
require "set"
require "keymap"

require "plugins.comment"
require "plugins.telescope"
require "plugins.lualine"
require "plugins.blankline"
require "plugins.gitsigns"
require "plugins.treesitter"
require "plugins.LSP"
require "plugins.DAP"
require "plugins.copilot"
